"""initial migration

Revision ID: 001
Revises: 
Create Date: 2026-02-03 23:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('telefone', sa.String(length=20), nullable=True),
        sa.Column('senha_hash', sa.String(length=255), nullable=False),
        sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', 'SUSPENSO', name='clientestatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    
    op.create_table('conversas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cliente_id', sa.Integer(), nullable=False),
        sa.Column('numero_usuario', sa.String(length=20), nullable=False),
        sa.Column('estado', sa.Enum('IA_ATIVA', 'AGUARDANDO_HUMANO', 'HUMANO_RESPONDEU', name='conversaestado'), nullable=False),
        sa.Column('ultima_mensagem', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversas_cliente_id'), 'conversas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_conversas_id'), 'conversas', ['id'], unique=False)
    op.create_index(op.f('ix_conversas_numero_usuario'), 'conversas', ['numero_usuario'], unique=False)
    
    op.create_table('mensagens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversa_id', sa.Integer(), nullable=False),
        sa.Column('tipo', sa.String(length=20), nullable=False),
        sa.Column('conteudo', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['conversa_id'], ['conversas.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_conversa_id'), 'mensagens', ['conversa_id'], unique=False)
    op.create_index(op.f('ix_mensagens_id'), 'mensagens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_id'), table_name='mensagens')
    op.drop_index(op.f('ix_mensagens_conversa_id'), table_name='mensagens')
    op.drop_table('mensagens')
    op.drop_index(op.f('ix_conversas_numero_usuario'), table_name='conversas')
    op.drop_index(op.f('ix_conversas_id'), table_name='conversas')
    op.drop_index(op.f('ix_conversas_cliente_id'), table_name='conversas')
    op.drop_table('conversas')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
